export { default as FeaturedWorks } from "./FeaturedWorks.astro"
export { default as Hero } from "./Hero.astro"
export { default as MovingLines } from "./MovingLines.astro"
export { default as WhoAmi } from "./WhoAmi.astro"
export { default as Works } from "./Works.astro"
